export type Passport = {
  name: string,
  surname: string,
  middlename: string,
  nationality: string,
  birthdate: string,
  country: string,
  gender: string,
  series: number,
  number: number,
  issue_date: string,
  issuing_organization: string,
  registration_address: {
    region: string,
    neighborhood: string,
    city: string,
    street: string,
    house: string,
    housing: string,
    building: string,
    apartment: string,
    index: number,
  },
  living_address: {
    region: string,
    neighborhood: string,
    city: string,
    street: string,
    house: string,
    housing: string,
    building: string,
    apartment: string,
    index: number,
  },
  first_photo: string,
  second_photo: string,
  selfie: string,
}

export type Paper = {
  country: string,
  registration_form: string,
  name: string,
  registration_number: number,
  address: {
    region: string,
    neighborhood: string,
    city: string,
    street: string,
    house: string,
    housing: string,
    building: string,
    apartment: string,
    index: number,
  },
  website: string,
  first_photo: string,
  second_photo: string,
  third_photo: string,
}