export enum UserRoles {
  borrower = "Заемщик",
  collector = "Коллектор",
  depositor = "Инвестор",
  creditor = "Кредитор",
}
export type Role = keyof typeof UserRoles;

export type UserData = {
  email: string,
  password: string,
  role: string,
  phone: string,
  tonwallet: string,
  passport: {
    name: string,
    surname: string,
    middleName: string,
    birthdate: string,
    country: string,
    gender: string,
    series: number,
    number: number,
    issue_date: string,
    issuing_organization: string,
    registration_address: {
      region: string,
      neighborhood: string,
      city: string,
      street: string,
      house: string,
      housing: string,
      building: string,
      apartment: string,
      index: number,
    },
    living_address: {
      country: string,
      region: string,
      neighborhood: string,
      city: string,
      street: string,
      house: string,
      housing: string,
      building: string,
      apartment: string,
      index: number,
    },
    first_photo: string,
    second_photo: string,
    selfie: string,
  },
  paper: {
    country: string,
    registration_form: string,
    name: string,
    registration_number: number,
    address: {
      region: string,
      neighborhood: string,
      city: string,
      street: string,
      house: string,
      housing: string,
      building: string,
      apartment: string,
      index: number,
    },
    website: string,
    first_photo: string,
    second_photo: string,
    third_photo: string,
  },
}